# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1A1E)
$foreground = rgb(BADFE8)
$color0 = rgb(404145)
$color1 = rgb(191323)
$color2 = rgb(4D0E2C)
$color3 = rgb(791548)
$color4 = rgb(950939)
$color5 = rgb(B4063E)
$color6 = rgb(2C7B8E)
$color7 = rgb(94C9D6)
$color8 = rgb(688D96)
$color9 = rgb(21192F)
$color10 = rgb(66133B)
$color11 = rgb(A21C60)
$color12 = rgb(C70B4C)
$color13 = rgb(F00853)
$color14 = rgb(3AA4BE)
$color15 = rgb(94C9D6)
