[Paths]
Prefix = ../../../../..
Libraries = usr/pyenv/lib/python3.10/site-packages/PySide6/Qt/lib
LibraryExecutables = usr/pyenv/lib/python3.10/site-packages/PySide6/Qt/libexec
Plugins = usr/pyenv/lib/python3.10/site-packages/PySide6/Qt/plugins
QmlImports = usr/pyenv/lib/python3.10/site-packages/PySide6/Qt/qml
Qml2Imports = usr/pyenv/lib/python3.10/site-packages/PySide6/Qt/qml
