# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #BADFE8
background         #1A1A1E
cursor             #907992

active_tab_foreground     #1A1A1E
active_tab_background     #BADFE8
inactive_tab_foreground   #BADFE8
inactive_tab_background   #1A1A1E

active_border_color   #BADFE8
inactive_border_color #1A1A1E
bell_border_color     #191323

color0      #404145
color1		#191323
color2		#4D0E2C
color3		#791548
color4		#950939
color5		#B4063E
color6		#2C7B8E
color7		#94C9D6
color8		#688D96
color9		#21192F
color10		#66133B
color11		#A21C60
color12		#C70B4C
color13		#F00853
color14		#3AA4BE
color15		#94C9D6
